Sprint9
NoK1R1LL/filmorate-java pull request #1
Opened 2023-09-15 08:58 UTC by NoK1R1LL

2023-09-15 15:52 UTC, Yang-Pi requested changes

2023-09-15 15:52 UTC, Yang-Pi commented on .idea/encodings.xml
Вот этот файл как и вся папка .idea должен попадать под .gitignore. Ты не менял .gitignore файл?

2023-09-15 15:52 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/service/FilmService.java
> +        film.setId(nextFilmId++);
Сделай метод generateId, как был в TaskManager

2023-09-15 15:52 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/service/FilmService.java
> +        films.add(film);
Не увидел валидации на правило "дата релиза — не раньше 28 декабря 1895 года"

2023-09-15 15:52 UTC, Yang-Pi commented
+ "Добавьте логирование для операций, которые изменяют сущности — добавляют и обновляют их. "

2023-09-16 10:53 UTC, merged

2023-09-16 11:17 UTC, NoK1R1LL commented on .idea/encodings.xml
Нет

2023-09-16 15:07 UTC, NoK1R1LL commented
Исправил